- hosts: localhost

  vars_files:
    - vars_mysql.yml

  tasks:
    - name: "Create user: {{ user_name }}"
      mysql_user:
        login_host: "{{ login_host }}"
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
        host: "{{ subnet_client }}"
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        state: present
        priv: "*.*:USAGE"
        update_password: on_create
      when: state == 'add'
                
    - name: "Set and update roles for all tables in {{ databases.ro }} for user: {{ user_name }}"
      mysql_user:
        login_host: "{{ login_host }}"
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
        host: "{{ subnet_client }}"
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        state: present
        append_privs: yes
        priv: "{{ item }}.*:{{ databases.grants_ro }}"
      with_items:
        - '{{ databases.ro }}'
      when:
        - state == 'add'
        - item[0] is defined

    - name: "Set and update roles for all tables in {{ databases.rw }} for user: {{ user_name }}"
      mysql_user:
        login_host: "{{ login_host }}"
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
        host: "{{ subnet_client }}"
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        state: present
        append_privs: yes
        priv: "{{ item }}.*:{{ databases.grants_rw }}"
      with_items:
        - '{{ databases.rw }}'
      when:
        - state == 'add'
        - item[1] is defined

    - name: "Remove and revoke all privileges from {{ user_name }} account"
      mysql_user:
        login_host: "{{ login_host }}"
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
        host: "{{ subnet_client }}"
        name: "{{ user_name }}"
        state: absent
      when: state == 'delete'

