version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-server
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=admin
      #- MYSQL_USER=admin
      #- MYSQL_DATABASE=prod
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

