version: '2.4'
services:
    postgres:
        image: postgres:12
        container_name: psql-server
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=admin
        ports:
          - 5432:5432
        deploy:
          resources:
            limits:
                cpus: 0.50
                memory: 128M
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-web
        restart: always
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@admin.com
          - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
          - 16543:80
        deploy:
          resources:
            limits:
                cpus: 0.50
                memory: 512M
        depends_on:
          - postgres

